Tensor is generalization of vectors and matrices and is understood as a multi-dimensional array. A vector is a one-dimensional or first order tensors and matrix is a 2-dimensional or second order tensor

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
#Rank zero tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#Rank one tensor
rank_1_tensor = tf.constant([4.0,5.0,6.0])
print(rank_1_tensor)

tf.Tensor([4. 5. 6.], shape=(3,), dtype=float32)


In [ ]:
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]],dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
rank_3_tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
#convert tensor to numpy
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1,1],[1,1]])
print(tf.add(a,b)) #element wise addition
print(tf.multiply(a,b)) #element wise multiplication
print(tf.matmul(a,b)) #matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [ ]:
#various operations on tensor
c=tf.constant([[4.0,5.0],[10.0,1.0]])
#Find the largest value
print(tf.reduce_max(c))
#Find the index of the largest value
print(tf.argmax(c))
#Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [ ]:
#ragged tensors
ragged = tf.ragged.constant([[5, 2, 6, 1], [], [4, 10]])
print(ragged)

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10]]>


In [ ]:
#string tensors
string_tensor = tf.constant("TensorFlow")
print(string_tensor)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
