In [ ]:
#Import libraries
import numpy as np
import torch

- Pytorch provides 2 data primitives: torch.utils.data.DataLoader and torch.utils.data.Dataset that allow you to pre-loaded datasets as well as your own data.
- Dataset stores the samples and their corresponding labels and DataLoader wraps an iterable around the dataset to enable easy access to the samples.

## **Loading a Dataset**

Here is an example of how to load the Fashion-MNIST dataset from TorchVision. We load FashionMNIST Datset with the following parameters:
- root is the path where tain/test data is stored.
- train specifies training or test dataset.
- download=True downloads the data from the internet if it's not available at root
- transform and target_transform specify the feature and label transformations.

In [ ]:
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor,Lambda
import matplotlib.pyplot as plt

training_data=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data=datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

100%|██████████| 26.4M/26.4M [00:01<00:00, 17.7MB/s]
100%|██████████| 29.5k/29.5k [00:00<00:00, 271kB/s]
100%|██████████| 4.42M/4.42M [00:00<00:00, 5.05MB/s]
100%|██████████| 5.15k/5.15k [00:00<00:00, 10.7MB/s]


## **Transforms**

- We use Transforms to perform some manipulation of the data and make it suitable for training
- All TorchVision datasets have 2 parameters - transform to modify the features and target_transform to modify the labels.

The FashionMNIST features are PIL Image  format, and labels are integers. For training,we need the features as normalized tensors and the labels as one hot encoded tensors. To make these transformations we use ToTensor and Lambda.

In [ ]:
#data transforms
from torchvision.transforms import ToTensor,Lambda

ds=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y:torch.zeros(10,dtype=torch.float).scatter_(0,torch.tensor(y),value=1))
)

- toTensor() ToTensor converts a PIL Image or Numpy ndarray into a FloatTensor and scales the image pixels intensity values in the range [0.,1.]
- Lambda Transforms apply any user-defined lambda function. Here, we define a function to turn the integer into a one-hot encoded tensor.

In [ ]:
#operations on Tensors
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"One Tensor: \n {ones_tensor} \n")
print(f"Zero Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.8701, 0.8045, 0.7648],
        [0.9054, 0.0571, 0.5923]]) 

One Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
tensor=torch.rand(3,4)
print(f"Shape: \n {tensor.shape} \n")
print(f"Datatype: \n {tensor.dtype} \n")
print(f"Device Tensor is stored in: \n {tensor.device} \n")

Shape: 
 torch.Size([3, 4]) 

Datatype: 
 torch.float32 

Device Tensor is stored in: 
 cpu 



In [ ]:
#Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
#Numpy to Tensor
t=torch.from_numpy(n)
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])
