## Practice-1
As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.
- temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]



**Steps to Perform:**

1. Explore the key attributes of NumPy arrays, including `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `data`.

In [4]:
import numpy as np
temperatures=np.array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ])
print("Dimension of NumPy: ",temperatures.ndim)
print("Shape of NumPy: ",temperatures.shape)
print("Size of NumPy: ",temperatures.size)
print("DataType of NumPy: ",temperatures.dtype)
print("Size of the items in NumPy: ",temperatures.itemsize)
print("Data in NumPy: ",temperatures)

Dimesnion of NumPy:  1
Shape of NumPy:  (7,)
Size of NumPy:  7
DataType of NumPy:  float64
Size of the items in NumPy:  8
Data in NumPy:  [75.2 77.1 74.5 79.3 82.6 81.2 77.8]


2. Demonstrate important NumPy array functions such as `reshape`, `flatten`, and `transpose`.

In [12]:
import numpy as np
temperatures=np.array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8,66.7])
#Reshape the array to (2,4)
reshaped=temperatures.reshape(2,4)
print("Reshape the array: ",reshaped)
#transpose of above array is (4,2)
print("transpose the array: ",reshaped.transpose())
#flatten the array to original 1 dimesnional array
print("Flatten the reshaped array: ",reshaped.flatten())

Reshape the array:  [[75.2 77.1 74.5 79.3]
 [82.6 81.2 77.8 66.7]]
transpose the array:  [[75.2 82.6]
 [77.1 81.2]
 [74.5 77.8]
 [79.3 66.7]]
Flatten the reshaped array:  [75.2 77.1 74.5 79.3 82.6 81.2 77.8 66.7]


## Practice-2

Consider the following arrays:

- Arrays for Arithmetic Operations:
  * Array A: [15, 25, 35, 45, 55]
  * Array B: [5, 10, 15, 20, 25]

- Array for Statistical Operations:
  * Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]

- Arrays for String Functions:
  * String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
  * String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']



__Steps to Perform:__

1. Perform element-wise addition, subtraction, multiplication, division, and power operations on Arrays A and B

In [17]:
A=np.array( [15, 25, 35, 45, 55])
B=np.array([5, 10, 15, 20, 25])
#Addition
print("Addition of 2 arrays",np.add(A,B))
#Subtraction
print("Subtraction of 2 arrays",np.subtract(A,B))
#Multiplication
print("Multiplication of 2 arrays",np.multiply(A,B))
#Division
print("Division of 2 arrays",np.divide(A,B))
#A to the power B
print("A to the power of B",np.power(A,B))

Addition of 2 arrays [20 35 50 65 80]
Subtraction of 2 arrays [10 15 20 25 30]
Multiplication of 2 arrays [  75  250  525  900 1375]
Division of 2 arrays [3.         2.5        2.33333333 2.25       2.2       ]
A to the power of B [     759375  1977800241 -2091638453 -1924594607   447042167]


2. Calculate the median, mean, standard deviation, and variance for Array C

In [23]:
C=np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])
#Mean
print("Mean of the values:",np.mean(C))
#Median
print("Median of the values:",np.median(C))
#Standard Deviation
print("Std of the values:",np.std(C))
#Variance
print("Variance of the values:",np.var(C))

Mean of the values: 57.0
Median of the values: 57.0
Std of the values: 28.722813232690143
Variance of the values: 825.0


3. Concatenate corresponding elements of String Arrays X and Y

In [29]:
#import the numpy package
import numpy as np
X=np.array(['Hello ', 'Data ', 'Science ', 'Class ', 'Learners '])
Y=np.array(['World', 'Analysis', 'is', 'Fun', '2023'])
#add function is used to concat the strings
concat=np.char.add(X,Y)
concat

array(['Hello World', 'Data Analysis', 'Science is', 'Class Fun',
       'Learners 2023'], dtype='<U17')

4. Convert all elements in String Array X to uppercase

In [36]:
#upper is used to convert all characters into uppercase
upper=np.char.upper(X)
upper

array(['HELLO ', 'DATA ', 'SCIENCE ', 'CLASS ', 'LEARNERS '], dtype='<U9')

5. Replace a specific substring in String Array Y with another substring

   np.char.replace(arr, old, new, count=None)


In [49]:
import numpy as np

Y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])
replace = np.char.replace(Y, "Analysis", "Science")

print(replace)

['World' 'Science' 'is' 'Fun' '2023']


### Practice-3

1. Create a 1D NumPy array with at least 10 elements

In [51]:
import numpy as np
one_dim_arr=np.array([1,2,3,4,5,6])
one_dim_arr

array([1, 2, 3, 4, 5, 6])

2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns

In [52]:
import numpy as np
two_dim_arr=np.array([[1,2,3,4],[4,5,6,7],[8,9,2,1]])
two_dim_arr


array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 2, 1]])

3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns

In [53]:
import numpy as np
three_dim_arr=np.array([[[1,2,3],[4,5,6]],[[8,9,2],[4,5,9]]])
three_dim_arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[8, 9, 2],
        [4, 5, 9]]])

4. Accessing Elements in Arrays

In [62]:
one_dim_arr=np.array([1,2,3,4,5,6])
one_dim_arr[3]

4

5. Access and print various elements from 1D, 2D, and, 3D using positive indexing

In [63]:
one_dim_arr=np.array([1,2,3,4,5,6])
print(one_dim_arr[3])

two_dim_arr=np.array([[1,2,3,4],[4,5,6,7],[8,9,2,1]])
print(two_dim_arr[1][2])

three_dim_arr=np.array([[[1,2,3],[4,5,6]],[[8,9,2],[4,5,7]]])
print(three_dim_arr[1][1][2])

4
6
7


6. Perform and print some basic arithmetic operations (like addition, subtraction) using elements accessed from 1D, 2D, and, 3D arrays

In [68]:
#1 dimension array
A=np.array( [15, 25, 35, 45, 55])
B=np.array([5, 10, 15, 20, 25])
#Addition
print("Addition of 1-dim arrays:",np.add(A,B))
#Subtraction
print("Subtraction of 1-dim arrays:",np.subtract(A,B))
#Multiplication
print("Multiplication of 1-dim arrays:",np.multiply(A,B))
#Division
print("Division of 1-dim arrays:",np.divide(A,B))
#A to the power B
print("A to the power of B:",np.power(A,B))

print("------------------------------\n")
#2-dimensional array
A=np.array([[15, 25], [35, 45], [55,60]])
B=np.array([[5, 10],[15, 20], [25,30]])
#Addition
print("Addition of 2-dim arrays",np.add(A,B))
#Subtraction
print("Subtraction of 2-dim arrays",np.subtract(A,B))
#Multiplication
print("Multiplication of 2-dim arrays",np.multiply(A,B))
#Division
print("Division of 2-dim arrays",np.divide(A,B))
#A to the power B
print("A to the power of B",np.power(A,B))

print("------------------------------\n")
#3-dimensional array
A=np.array([[[1,2,3],[4,5,6]],[[8,9,2],[4,5,7]]])
B=np.array([[[1,2,4],[4,9,6]],[[2,3,2],[4,0,7]]])
#Addition
print("Addition of 3-dim arrays",np.add(A,B))
#Subtraction
print("Subtraction of 3-dim arrays",np.subtract(A,B))
#Multiplication
print("Multiplication of 3-dim arrays",np.multiply(A,B))
#Division
print("Division of 3-dim arrays",np.divide(A,B))
#A to the power B
print("A to the power of B",np.power(A,B))

Addition of 1-dim arrays: [20 35 50 65 80]
Subtraction of 1-dim arrays: [10 15 20 25 30]
Multiplication of 1-dim arrays: [  75  250  525  900 1375]
Division of 1-dim arrays: [3.         2.5        2.33333333 2.25       2.2       ]
A to the power of B: [     759375  1977800241 -2091638453 -1924594607   447042167]
------------------------------

Addition of 2-dim arrays [[20 35]
 [50 65]
 [80 90]]
Subtraction of 2-dim arrays [[10 15]
 [20 25]
 [30 30]]
Multiplication of 2-dim arrays [[  75  250]
 [ 525  900]
 [1375 1800]]
Division of 2-dim arrays [[3.         2.5       ]
 [2.33333333 2.25      ]
 [2.2        2.        ]]
A to the power of B [[     759375  1977800241]
 [-2091638453 -1924594607]
 [  447042167           0]]
------------------------------

Addition of 3-dim arrays [[[ 2  4  7]
  [ 8 14 12]]

 [[10 12  4]
  [ 8  5 14]]]
Subtraction of 3-dim arrays [[[ 0  0 -1]
  [ 0 -4  0]]

 [[ 6  6  0]
  [ 0  5  0]]]
Multiplication of 3-dim arrays [[[ 1  4 12]
  [16 45 36]]

 [[16 27  4]
  

C:\Users\Keert\AppData\Local\Temp\ipykernel_2056\3855403712.py:41: RuntimeWarning: divide by zero encountered in divide
  print("Division of 3-dim arrays",np.divide(A,B))


7. Access and print elements using negative indices in all three arrays

   In negative indices , count starts at 1 from behind not 0 

In [70]:
one_dim_arr=np.array([1,2,3,4,5,6])
print(one_dim_arr[-3])

two_dim_arr=np.array([[1,2,3,4],[4,5,6,7],[8,9,2,1]])
print(two_dim_arr[-1][-2])

three_dim_arr=np.array([[[1,2,3],[4,5,6]],[[8,9,2],[4,5,7]]])
print(three_dim_arr[-1][-1][-2])

4
2
5


### Practice-4
- Creating arrays for slicing:
    * Create a 1D NumPy array with at least 15 elements
- Slicing 1D arrays:
    * Perform and demonstrate different slices on the 1D array, explore it using step values

In [71]:
one_dim_arr=np.array([1,2,3,4,5,6,7,8,9,3,4,5,3,2,6])
one_dim_arr[2:6]

array([3, 4, 5, 6])

- Creating arrays for slicing:
  * Create a 2D NumPy array with a minimum of 4 rows and 5 columns
- Slicing 2D arrays:
  * Slice rows and columns separately and in combination

In [78]:
two_dim_arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[8,9,2,1,6],[4,5,6,3,2]])
print(two_dim_arr[1][1:4])
print(two_dim_arr[1:3][1])

[5 6 7]
[8 9 2 1 6]


- Creating arrays for slicing:
   * Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns
- Slicing 3D arrays:
  * Perform slicing to access different matrices, rows within matrices, and elements within row


In [84]:
three_dim_arr=np.array([[[1,2,3],[4,5,6]],[[8,9,2],[4,5,7]]])
three_dim_arr[1][0:2][1]

array([4, 5, 7])

Negative slicing:
  * Implement negative slicing on 1D, 2D, and 3D arrays
  * Compare the outcomes of negative slicing with positive slicing


In [92]:
one_dim_arr=np.array([1,2,3,4,5,6])
print(one_dim_arr[-4:-1])

two_dim_arr=np.array([[1,2,3,4],[4,5,6,7],[8,9,2,1]])
print(two_dim_arr[-1][-4:-1])

three_dim_arr=np.array([[[1,2,3],[4,5,6]],[[8,9,2],[4,5,7]]])
print(three_dim_arr[-1][-1][-3:-1])

[3 4 5]
[8 9 2]
[4 5]
