## Practice-1
You are given two matrices, A and B. Use the NumPy library to perform various matrix operations. This exercise will help you grasp the fundamental concepts of linear algebra and their application in Python.
Here are the two matrices:dd Matrix A and Matrix B


### Steps to Perform:

1. Add Matrix A and Matrix B

In [16]:
import numpy as np
A=np.array([[4,7],[2,6]])
B=np.array([[5,8],[3,4]])
sum=A+B
sum

array([[ 9, 15],
       [ 5, 10]])

2. Multiply Matrix A and Matrix B

In [17]:
multi=A*B
multi

array([[20, 56],
       [ 6, 24]])

3. Transpose Matrix A

In [19]:
print(A)
print(np.transpose(A))

[[4 7]
 [2 6]]
[[4 2]
 [7 6]]


4. Find the determinant of Matrix B

In [24]:
np.linalg.det(B)

-3.999999999999999

5. Find the inverse of Matrix A (if it exists)

In [ ]:
np.linalg